services:
  postgres:
    image: postgres:16
    container_name: amiya_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: amiya_db
    volumes:
      - amiya_pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: amiya_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   
      - "9001:9001"   
    volumes:
      - amiya_minio_data:/data

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ingress-net"

      - "--entrypoints.postgres.address=:5432"
      - "--entrypoints.mysql.address=:3306"
      - "--entrypoints.mssql.address=:1433"
      - "--entrypoints.mongodb.address=:27017"

      - "--providers.file.directory=/certs"
      - "--providers.file.watch=true"

      - "--api.dashboard=true"
      - "--api.insecure=true"

    ports:
      - "5432:5432"    # PostgreSQL
      - "3306:3306"    # MySQL
      - "1433:1433"    # MSSQL
      - "27017:27017"  # MongoDB
      - "8080:8080"    # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs:ro"
    networks:
      - ingress-net

networks:
  ingress-net:
    external: true

volumes:
  amiya_pgdata:
    driver: local
  amiya_minio_data:
    driver: local
